version: '3.8'
services:
  calo-analysis:
    build: .
    volumes:
      - ./data-cleaned:/app/data        # Mount cleaned data here
      - ./output:/app/output
    environment:
      - PYSPARK_PYTHON=python3
    command: ["spark-submit", "--master", "local[*]", "src/main.py"]

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data-cleaned:/app/data       # Same data mount for Streamlit
      - ./output:/app/output
      - ./src:/app/src                 # Mount your source for Streamlit app
    command: streamlit run src/app.py --server.enableCORS=false --server.port=8501 --server.address=0.0.0.0
